title: Dhiganth Rao
subtitle: 19 year old UG Student
description: >- # this means to ignore newlines until "baseurl:"
  devlopr-jekyll is a Jekyll Theme Built For Developers

url: "" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

urls:
    - text: About Me
      url: /about
    # - text: Blog
    #  url: /blog
    - text: Contact Me 
      url : /contact
    - text: Get Started
      url: /get-started

# Edit these details

author_logo: 
author: Dhiganth Rao
author_bio: Hi, my name is Dhiganth Rao. 
author_email: "dhiganth00@gmail.com"
author_location: India
# author_website_url: "https://dhiganthrao.github.io"
typewrite-text: I'm interested in Machine Learning, Deep Learning and coding!

author_work_experiences:
            - company_name: Solarillion Foundation
              company_logo: solarillion.jpg
              company_url: https://solarillion.github.io
              designation: Undergraduate Research Assistant
              description: Working on Projects Related to Machine Learning and Deep Learning.
              visibility: true
            

author_education_details:
              - college_logo: ssn.jpg
                college_name: SSN College of Engineering
                college_url: www.ssn.edu.in
                college_degree: Electronics and Communication Engineering
                description: Bachelor of Engineering
                visibility: true

author_project_details:
              - project_thumbnail: 
                project_title: Zeus
                project_description: A Discord Bot focused on Moderation.
                #project_url: 
                visibility: true
              - project_thumbnail: 
                project_title: BunkBot
                project_description: A Python Script to attend your online classes for you!
                project_url: https://github.com/dhiganthrao/bunk_bot
                visibility: true

# social links
twitter_username: dhiganthrao
github_username:  dhiganthrao
facebook_username: pokemeister9899
linkedin_username: dhiganthrao


#for comments ( we got Disqus and Hyvor Commenting, uncomment the one you want to use )

# disqus_shortname: sujay-kundu
# hyvor_talk_website_id: 476

# wakatime username (coding activity)
wakatime_username: dhiganthrao

# mailchimp embedded form url (newsletter):
# mailchimp_form_url: https://sujaykundu.us10.list-manage.com/subscribe/post?u=50bab1c85eae24ecfb0f68361&amp;id=3a2dd721d0

# formspree (contact form)
formspree_email: dhiganth00@gmail.com

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# Choose what to show (can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true

# algolia search
# algolia:
#  application_id: D9WA1YKTRQ
#  index_name: blog_posts # You can replace that with whatever name you want
#  files_to_exclude: []
#  nodes_to_index: 'article'
#  search_only_api_key: 58ffdd7cd6c45ec1577a7fcd789b1b9a

# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'

# Shop
#collections:
# - products

# Gallery
#defaults:
#  -
#    scope:
#      path: "gallery"
#    values:
#      permalink: /:path/:basename:output_ext

# Build settings
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-algolia
  - jekyll-menus


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - _includes/blog_newsletter.html

destination: ./build
